---
title: "FirstQuatro"
format: html
editor: visual
---

# First Quatro

```{r}
library(tidyverse)
library(ggplot2)
library(ggdist)
library(nycflights13)
```



## Ny Txt

## Text

```{r}
1+1
```

```{r}
url <- "https://www.nav.no/_/attachment/download/c0985215-d99f-4f61-956d-302034bcd0ec:0d32f598ec46743086dddc992a651e9b5ccb8d94/HL301%20Helt%20ledige.%20Fylke%20kommune.%20August%202026.%20CSV.csv"

ledighet <- read_delim(url, delim = ";", 
                        locale = locale(encoding = "Latin1"),
                        show_col_types = FALSE) %>% 
  mutate(
    `Antall helt ledige` = na_if(`Antall helt ledige`, "*") %>% as.numeric(),
    `Helt ledige i prosent av arbeidsstyrken` = na_if(`Helt ledige i prosent av arbeidsstyrken`, "*") %>% 
      str_replace(",", ".") %>% as.numeric()
  )

rogaland <- ledighet %>% filter(Fylkenavn == "Rogaland")
```

```{r}
view(rogaland)
```

```{r}
rogaland_t <- rogaland %>% 
  column_to_rownames("Kommunenavn") %>% 
  t() %>% 
  as_tibble(rownames = "variabel")
```

```{r}
library(tidyverse)

mtcars %>% 
  rownames_to_column("model") %>% 
  filter(model %in% c("Lotus Europa", "Maserati Bora", "Porsche 914.2")) %>% 
  pull(mpg)
```

```{r}
view(rogaland_t)

```

```


```{r}

```



```{r}
ggplot(
  data = mtcars, 
  mapping = aes(x = disp, y = mpg)
)+
  geom_point()
```


```{r}
ggplot(
  data = mtcars,
  mapping = aes(x = disp, y = mpg)
)+ geom_point(
  mapping = aes(colour = "black")
)
```

```

```{r}
mtcars
```

```{r}
ggplot(mtcars, aes(x = disp, y = mpg)) +
  geom_point(aes(colour = hp, size = wt, shape = factor(cyl))) +
  geom_smooth(method = "lm", level = 0.99, colour = "gray90") +
  geom_smooth(method = "lm", level = 0.95, colour = "gray60") +
  geom_smooth(method = "lm", level = 0.90, colour = "gray20") +
  
```
```{r}
ggplot(mtcars, aes(x = disp, y = mpg)) +
  stat_lineribbon(aes(y = mpg), .width = ppoints(5000), alpha = 0.1) +  # gradient automatisk
  geom_point(aes(colour = hp, size = wt, shape = factor(cyl)))
```
```{r}
tibblemtcars = mtcars |> 
  as_tibble()
```
```{r}
install.packages("starwars dataset")
```


```{r}
print(flights[10:19])
```


```{r}

set.seed(1234)
res_mean_rnorn <- paste("result: ", 
                        round(mean(
                          rnorm(n=10, mean = 0,sd = 1)), digits=5), 
                        sep ="")
res_mean_rnorn
```
```{r}
set.seed(1234)
res1234 <- rnorm(n = 10, mean = 0, sd = 1) |> 
  mean() |> 
  round(digits = 3) %
res1234
```

```{r}
view(flights)
```




```{r}
set.seed(1234)
res12345 <- rnorm(n = 10, mean = 0, sd = 1) |> 
  mean() |> 
  round(digits = 3) |> 
  (\(x) paste("Result: ", x))()   # \(x) is a native pipe lambda, x = the rounded value
res12345
```
```{r}
flights <- get(data(flights))
```

## Antall flights i april og septemer

```{r}

flights |> 
  filter(month == 4L | month == 9L) |> 
  nrow()


```
```{r}
```


```{r}
flights |> 
  filter(month %in% c(4L, 9L)) |> 
  nrow()
```


```{r}


flights |> 
  filter(day %in% c(1, 2)) |> 
  nrow()

```
```{r}
flights |> 
  filter(arr_delay >= 15 & arr_delay < 30) |>
nrow()
```



